services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vocab_flashcard
    volumes:
      - vocab_pgdata:/var/lib/postgresql/data

  api:
    build: ./apps/api
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/vocab_flashcard
      NODE_ENV: production
      PORT: 3000
      JWT_SECRET: 56df22d6b5b72b9f5cf56cd7542d088dfadfdd913163705da205d89235446b6fa1d243dae8c0a1baf280732bf17a82850ae58214c4da3cc44ae037706221476e
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && npm run start"
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  vocab_pgdata:
